### ISSUE TITLE
Version 4.0 roadmap

### ISSUE THREAD

**Issue by TheDevtop** [TheDevtop/exm#2]
- [x] Configure GitHub actions
- [x] Create list abstraction (Vec<String>)
- [ ] Add index functions api_index(), table_index()
- [x] Check if CORS policies are necessary
- [x] Add append function
- [x] Add replace function, returns old values
- [ ] Search with regular expressions

**Comment by TheDevtop** [comment]
This project has stalled, so I'll close this issue and archive the repository.
